version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Show .NET Version
          command: dotnet --version

      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build --no-restore

      - run:
          name: Test
          command: dotnet test --no-build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
