version: 2.1

jobs:
  build:
    docker:
      # Match your local SDK (10.0.103)
      - image: mcr.microsoft.com/dotnet/sdk:10.0

    steps:
      - checkout

      - run:
          name: Show workspace
          command: |
            pwd
            ls

      - run:
          name: Locate project file
          command: find . -name "*.csproj"

      - run:
          name: Restore project
          command: dotnet restore

      - run:
          name: Build project
          command: dotnet build

      - run:
          name: Run project
          command: dotnet run

workflows:
  build_and_test:
    jobs:
      - build
