
version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:10.0

    steps:
      - checkout

      - run:
          name: Restore
          command: dotnet restore firstapp/firstapp.csproj

      - run:
          name: Build
          command: dotnet build firstapp/firstapp.csproj

      - run:
          name: Run
          command: dotnet run --project firstapp/firstapp.csproj

workflows:
  build_and_test:
    jobs:
      - build
