version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - checkout

      - run:
          name: Show files
          command: ls

      - run:
          name: Move into project folder
          command: cd firstapp

      - run:
          name: Restore
          command: dotnet restore firstapp.csproj

      - run:
          name: Build
          command: dotnet build firstapp.csproj

      - run:
          name: Run
          command: dotnet run --project firstapp.csproj

workflows:
  build_and_test:
    jobs:
      - build
