version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - checkout

      - run:
          name: Show full directory tree
          command: |
            pwd
            ls
            find . -name "*.csproj"

      - run:
          name: Enter project directory
          command: cd $(dirname $(find . -name "*.csproj" | head -n 1))

      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build

      - run:
          name: Run
          command: dotnet run

workflows:
  build_and_test:
    jobs:
      - build
